### PR TITLE
[F] Add investigations to related content

### PR DESCRIPTION
**Pull request by jen-castiron**
- Adds investigations to related content
- Uses landingPage uri for uri
- No description field on investigations yet, will need to be added to the backend/API first

### CODE REVIEW

**Review by dananjohnson — CHANGES_REQUESTED** [review]
@jen-castiron I believe `description` has been added to the API now. I also think Kyle configured investigations to return `landingPage.uri` as its own `uri`. That might simplify the frontend a bit.

**Comment by blnkt** [comment]
sorry I broke your stuffs with my force pushings, but Lucas thinks a rebase will getcha back on track A-ok.

**Comment by dananjohnson** [comment]
@jen-castiron I've rebased your branch to fix the merge conflicts. See my earlier change request before merging this in. Thanks!

**Comment by jen-castiron** [comment]
@dananjohnson Updated with description and uri! However, the uri is returning as `null` so I kept the landing page in as a fallback. @kylepratuch Should I expect the investigation's landing page to be returned as the top level uri? Or is it `null` expected?

**Review by dananjohnson — APPROVED** [review]
Giving my 👍🏻 on this. We'll see what Kyle says, but I think the fallback makes sense.

**Comment by kylepratuch** [comment]
> @kylepratuch Should I expect the investigation's landing page to be returned as the top level uri? Or is `null` expected?

I had hoped you would get the landing page based on the Investigation configuration, assuming that relation exists. I'll double check that and follow up.

**Pull request merged**
